### ISSUE TITLE
[Question] Do you still need a service like pythonanywhere with this function to work?

### ISSUE THREAD

**Issue by Dvalin21** [alexbn71/AgentDVR-Telegram#1]
As said in titled. 

Currently using Smtp to telegram and it requires an outside service. pythonanywhere is free, but I would rather keep everything in house

**Comment by alexbn71** [comment]
@Dvalin21 here there are two solutions, one uses PHP so you have to hosts an Apache/PHP server somewhere in your private network but... the new one ueses the script engine provided by AgentDVR so no external service is required.

**Comment by Dvalin21** [comment]
So I can install this and not have to have anything hosted our of the network? Which this would send a notification vs a smtp email?

**Comment by alexbn71** [comment]
You have to install it in AgentDVR "commands" folder. 
Why are you talking about smtp? This script does not make use of SMTP.... it pushes a notification directly to the Telegrem bot you have to create

**Comment by Dvalin21** [comment]
Sorry, I had just mentioned it because I was using smtp to telegram dvr. I
was trying to make sure I didn't need to set anything up outside like going
to pythonanywhere to make sure telegram got the notifications

Update: So just to be clear, after editing .sh and .php files, I place them on in the command folder correct?

**Comment by alexbn71** [comment]
You don't need PHP file if you are not planning to use Apache/PHP. Edit and copy only .sh in Commands folder.
