### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by nicomarti83** [alexbn71/AgentDVR-Telegram#2]
Hi,
I'm trying to use your telegram_sendphoto.sh but I think it miss somethink to work. 

What are APIUSER and APIPWD? Credentials used to connect to the web interface?
How can I consult logs from CURL command ?
Thanks in advance

**Comment by alexbn71** [comment]
Hi,  
take a look at this page: https://www.ispyconnect.com/userguide-agent-api.aspx

![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/20998190/6c3514d8-bd2a-4555-8cf3-3b17ff53c06f)

let me know if you need more help

**Comment by nicomarti83** [comment]
<img width="875" alt="Capture d’écran 2023-09-01 à 13 43 48" src="https://github.com/alexbn71/AgentDVR-Telegram/assets/18363363/8e5c6f39-211e-4346-99f5-576bedc5f044">
<img width="882" alt="Capture d’écran 2023-09-01 à 13 44 03" src="https://github.com/alexbn71/AgentDVR-Telegram/assets/18363363/69955940-13d3-4d1d-858d-5eacd092552a">
Ok, the auth problem is solved but the manual alert do nothing... no telegram notification and "grabs" folder empty...
However the script seem to work when I start it in the container, exept the jpg file into "grabs" is empty probably because the two parameters ({ID} '{MSG}') are missing. The result is an error from telegram api `error_code":400,"description":"Bad Request: file must be non-empty`.
So I guess my action configuration in agent dvr is bad but I don't understant why ...

**Comment by alexbn71** [comment]
I need to know your Commands folder path (the container path):

![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/20998190/ab0107d1-6a25-4d86-bc86-af307458f590)

I think you have to update this path...
![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/20998190/841406fa-92b7-47cd-90bf-e70c7dda9777)

**Comment by nicomarti83** [comment]
in the HOST : /home/xxx/docker/agent-dvr/Commands
in container : /AgentDVR/Commands

**Comment by alexbn71** [comment]
> in the HOST : /home/xxx/docker/agent-dvr/Commands in container : /AgentDVR/Commands

Ok check the path in the script... and do the necessary changes

**Comment by nicomarti83** [comment]
I think I alrealy change the path.

<img width="1219" alt="Capture d’écran 2023-09-01 à 18 01 10" src="https://github.com/alexbn71/AgentDVR-Telegram/assets/18363363/014850ca-4bb6-4f67-8864-102560f68097">

**Comment by alexbn71** [comment]
> I think I alrealy change the path.
> 
> <img alt="Capture d’écran 2023-09-01 à 18 01 10" width="1219" src="https://user-images.githubusercontent.com/18363363/265071096-014850ca-4bb6-4f67-8864-102560f68097.png">

Test the URL in your browser... ie in my case: http://mininas-2:8090/grab.jpg?oid=13&size=1280x720&maintainAR=true

remember to replace "${AGENTDVRURL}" and ${ID} variables and check the port, in my case 8090

the browser should show a frame of your cam

**Comment by nicomarti83** [comment]
After being prompted for my credentials it work.

**Comment by nicomarti83** [comment]
Hum... after making lots of tests (changing folders rights, restarting my docker, rebuilt the action from begining) I finaly receve pictures (of the begining of the recording) on telegram without text... I don't know what unblocked the situation... I continue to investigate about the missing text and the useless picture.

**Comment by alexbn71** [comment]
Why "useless picture"?

**Comment by nicomarti83** [comment]
Useless because the event who trigger the script is always missing from the picture... I think because I configure somewhere (don't know where)a pre alert recording.

**Comment by alexbn71** [comment]
I noticed that on "Manual Alert" the MSG variable is set to "Manual Alert" (and telegram receive a picture with text) but on motion detect AgentDVR does not set MSG 

on my old telegram notifications the image was received with "Alert" text (on motion detect). It seems that something changed recently

**Comment by alexbn71** [comment]
I noticed that there is a new variable implemented by AgentDVR {BASE64IMAGE}. For this reason I have changed the script... now it does't needs API access and the image sent is exactly the one captured by AgentDVR event. You could try this new version 

NB: Remember to update the Task Parameters to {ID} '{MSG}' {BASE64IMAGE}

**Comment by nicomarti83** [comment]
The script seem to work with the manual alert, the resolution is low but suffisiant to figure what's going on. I'll try tomorow to see if it capture the alert event. Thank's a lot for the improvement.

**Comment by alexbn71** [comment]
With {BASE64IMAGE} solution is AgentDVR that set the resolution. The old solution that uses AgentDVR API was setting the resolution to 1280x720

**Comment by nicomarti83** [comment]
Everything seem to work fine now, thank you for helping.
