### ISSUE TITLE
file cannot be found 

### ISSUE THREAD

**Issue by spudnvrgmail** [alexbn71/AgentDVR-Telegram#5]
Gday , 

after installing and then activating a manual alert  , nothing happens  

checking the log it says it cannot find the file as below 

19:15:27       RunScript: /bin/bash -c "C:\Program Files\Agent\Commands\telegram_sendphoto.sh 1 'Manual Alert'
19:15:28	ProcessAlertEvent: The system cannot find the file specified at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at CoreLogic.Utilities.Helper.RunScript(String filename, String args, Boolean noWindow) at CoreLogic.Objects.Helpers.AlertProcessor.<ProcessAlertEvent>d__7.MoveNext()

my install directory is \agent\   and the files in the commands folder 

am i missing something ? 

thanks!

**Comment by jmvl** [comment]
It's case sensitive, try to edit the sh file and replace Agent with agent
